# Generated by Django 5.0.1 on 2024-01-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0002_alter_quizquestion_correct_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(max_length=255),
        ),
    ]
